### ISSUE TITLE
I can't compile it in  Kali linux 

### ISSUE THREAD

**Issue by merlinnusr** [abhijeet2096/TL-WN722N-V2#1]

**Comment by abhijeet2096** [comment]
Please provide the output of `uname -r`

**Comment by merlinnusr** [comment]
I use it in a  VM in VMware 

uname -r 
4.13.0-kali1-amd64



root@kali:~/p/TL-WN722N-V2# make all 
"******************************************"
"NO SKRC,we will use default KSRC"
"******************************************"
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.13.0-kali1-amd64/build M=/root/p/TL-WN722N-V2  modules
make[1]: se entra en el directorio '/usr/src/linux-headers-4.13.0-kali1-amd64'
"******************************************"
"NO SKRC,we will use default KSRC"
"******************************************"
  CC [M]  /root/p/TL-WN722N-V2/core/rtw_cmd.o
In file included from /root/p/TL-WN722N-V2/include/drv_types.h:32:0,
                 from /root/p/TL-WN722N-V2/core/rtw_cmd.c:22:
/root/p/TL-WN722N-V2/include/osdep_service.h: In function ‘thread_enter’:
/root/p/TL-WN722N-V2/include/osdep_service.h:342:2: error: implicit declaration of function ‘allow_signal’ [-Werror=implicit-function-declaration]
  allow_signal(SIGTERM);
  ^~~~~~~~~~~~
/root/p/TL-WN722N-V2/include/osdep_service.h: In function ‘flush_signals_thread’:
/root/p/TL-WN722N-V2/include/osdep_service.h:352:6: error: implicit declaration of function ‘signal_pending’ [-Werror=implicit-function-declaration]
  if (signal_pending (current))
      ^~~~~~~~~~~~~~
/root/p/TL-WN722N-V2/include/osdep_service.h:354:3: error: implicit declaration of function ‘flush_signals’ [-Werror=implicit-function-declaration]
   flush_signals(current);
   ^~~~~~~~~~~~~
cc1: some warnings being treated as errors
/usr/src/linux-headers-4.13.0-kali1-common/scripts/Makefile.build:307: fallo en las instrucciones para el objetivo '/root/p/TL-WN722N-V2/core/rtw_cmd.o'
make[4]: *** [/root/p/TL-WN722N-V2/core/rtw_cmd.o] Error 1
/usr/src/linux-headers-4.13.0-kali1-common/Makefile:1529: fallo en las instrucciones para el objetivo '_module_/root/p/TL-WN722N-V2'
make[3]: *** [_module_/root/p/TL-WN722N-V2] Error 2
Makefile:145: fallo en las instrucciones para el objetivo 'sub-make'
make[2]: *** [sub-make] Error 2
Makefile:8: fallo en las instrucciones para el objetivo 'all'
make[1]: *** [all] Error 2
make[1]: se sale del directorio '/usr/src/linux-headers-4.13.0-kali1-amd64'
Makefile:1367: fallo en las instrucciones para el objetivo 'modules'
make: *** [modules] Error 2

**Comment by merlinnusr** [comment]
I can compile it in Linux mint 
uname -r 
4.10.0-33-generic

but not in Kali

**Comment by abhijeet2096** [comment]
Hey,

I added Support for kernel 4.13 . please follow below instructions.

1. clone repository again or pull
`git clone https://github.com/abhijeet2096/TL-WN722N-V2`
or 
move to previously cloned directory and type
`git pull`
2. Compile the above repository using make command
`sudo make all`
3.Compilation will/could give one warning ignore that and proceed to install.
`sudo make install`
4.Reboot the system
`sudo reboot`
5.For monitor mode follow readme.

**Comment by merlinnusr** [comment]
it works Thx :)
