### ISSUE TITLE
please compile TL-WN722N-V2 drivers for kernel 4.14.0-kali3-686-pae

### ISSUE THREAD

**Issue by rahulracrazy** [abhijeet2096/TL-WN722N-V2#10]
abhijeet sir, i request u to compile the TL-WN722N-V2 dr9iers for kali linux 4.14.0-kali3-686-pae.....
there are many waiting for ur new version kernel compiled....please post fastr as u can
or how can i compile on my own???
anyone HELP!

**Comment by rahulracrazy** [comment]
guys ## I found a way for latest kernel users @rahulracrazy

**Comment by abhijeet2096** [comment]
Sure , i will try to fix the issue that will enable to compile it for 4.14. I will try this in next week. Thanks

**Comment by abhijeet2096** [comment]
Hey Rahul check now , it should work  !

**Comment by rahulracrazy** [comment]
OHH THANK YOU SIR..U HELPED US A LOT

**Comment by tienquangbmt** [comment]
abhijeet sir, i request u to compile the TL-WN722N-V2 dr9iers for kali linux 4.14.0-kali3-amd64 .helped us a lot dienlanhtienquang@gmail.com thank you sir
