### ISSUE TITLE
The led of my TL-WN722N-V2 doesn't turn on 

### ISSUE THREAD

**Issue by merlinnusr** [abhijeet2096/TL-WN722N-V2#2]
uname -a 

> Linux moe 4.10.0-33-generic #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a

> No LSB modules are available.
> Distributor ID:	LinuxMint
> Description:	Linux Mint 18.2 Sonya
> Release:	18.2
> Codename:	sonya

**Comment by abhijeet2096** [comment]
Led is now switched ON permanently to switch it off follow Readme. Please make and install repository again !
