### ISSUE TITLE
Support of Linux Kernel 4.17

### ISSUE THREAD

**Issue by Lignium** [abhijeet2096/TL-WN722N-V2#23]
Hi, I compiled the driver under the newest kernel on Arch Linux. And when the system starts, the kernel panic drops out. Before compiling, I fixed the Makefile: https://github.com/lwfinger/rtl8188eu/issues/238#issuecomment-357497995

**Comment by hhenne1** [comment]
Support of Linux Kernel 4.17 (current Kali) would be great.. can't get any driver for it to work..

**Comment by abhijeet2096** [comment]
Thanks @Lignium for pointing it out, I will soon try to make it work in kernel 4.17 and ubuntu 18.04.

**Comment by MilosJovanovic50** [comment]
Any updates on support for kernel 4.17 ?

**Comment by abhijeet2096** [comment]
Could you try and post the error log? while making , please try the latest master branch
