### ISSUE TITLE
Unable to compile on raspberry pi

### ISSUE THREAD

**Issue by AmritSd** [abhijeet2096/TL-WN722N-V2#5]
Hello , I am trying to make my wifi adapter work with the raspberry pi 3 . But I get the following error -

`"******************************************"
"NO SKRC,we will use default KSRC"
"******************************************"
install -p -m 644 8188eu.ko  /lib/modules/4.9.35-v7+/kernel/drivers/net/wireless/
install: cannot stat ‘8188eu.ko’: No such file or directory
Makefile:1373: recipe for target 'install' failed
make: *** [install] Error 1
`
my kernel version is  4.9.35-v7+

I am a noob when it comes to linux . so, any help will be appreciated.
Thanks in advance.

**Comment by Dogcatfee** [comment]
You need the linux headers package, most likely `linux-headers`. By default these Makefiles try to cross compile when run on an ARM CPU, to get around this you can use `make ARCH=arm  -j4`. `-j4` just makes compiling faster, and is not required.

**Comment by abhijeet2096** [comment]
Hey , try to install "linux-headers" , and check again !
