### ISSUE TITLE
Sudo make all command error

### ISSUE THREAD

**Issue by tanmaybhawsar** [abhijeet2096/TL-WN722N-V2#6]
root@kali:~# cd '/root/Desktop/TL-WN722N-V2' 
root@kali:~/Desktop/TL-WN722N-V2# sudo make clean
"******************************************"
"NO SKRC,we will use default KSRC"
"******************************************"
cd hal/OUTSRC/ ; rm -fr */*.mod.c */*.mod */*.o */.*.cmd */*.ko
cd hal/OUTSRC/ ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko 
cd hal/led ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd hal ; rm -fr */*/*.mod.c */*/*.mod */*/*.o */*/.*.cmd */*/*.ko
cd hal ; rm -fr */*.mod.c */*.mod */*.o */.*.cmd */*.ko
cd hal ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd core/efuse ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd core ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd os_dep/linux ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd os_dep ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd platform ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
rm -fr Module.symvers ; rm -fr Module.markers ; rm -fr modules.order
rm -fr *.mod.c *.mod *.o .*.cmd *.ko *~
rm -fr .tmp_versions
root@kali:~/Desktop/TL-WN722N-V2# sudo make all
"******************************************"
"NO SKRC,we will use default KSRC"
"******************************************"
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.13.0-kali1-amd64/build M=/root/Desktop/TL-WN722N-V2  modules
make[1]: *** /lib/modules/4.13.0-kali1-amd64/build: No such file or directory.  Stop.
Makefile:1367: recipe for target 'modules' failed
make: *** [modules] Error 2

This is the error pls help

**Comment by abhijeet2096** [comment]
If possible downgrade  your kernel to 4.12 for now . 

Removing kernel could be difficult so you should install kernel 4.12 and boot from that kernel .after that the driver should compile !

Please provide  information about your kernel!

**Comment by abhijeet2096** [comment]
Hey, you should first install "linux-headers" package for your distribution and try again , it should work !
